package model;

import java.time.LocalDate;

/**
 * Model of an Assignment 
 * set ONLY by the Headmaster
 * <p>
 * An Assignment has a {@link model.Assignment#id unique id}, 
 * a {@link model.Assignment#courseId courseId}, 
 * a {@link model.Assignment#title title},  
 * a {@link model.Assignment#submissionDate submissionDate} and 
 * a {@link model.Assignment#description description}.
 *
 * @author Sakel
 * @version 1.0
 */
public class Assignment implements Persistable {

    /**
     * unique identifier of an assignment [int(11) auto increment PK] 
     * <p>
     * If this is a new assignment, and not an existing one taken from 
     * the database, then id is allowed to not be instantiated since id
     * will be <b>auto generated by the database</b> once the new assignment is inserted
     */
    private int id;
    
    /**
     * identifier of the course this assignment belongs to [int(11) not null]
     * <p>
     * If this is a new assignment then courseId must be provided explicitly
     * and has to belong to an existing course from the database
     * <p>
     * If this is an existing assignment taken from the database then courseId
     * is provided by the database and is a <b>FK (ON DELETE CASCADE) pointing to table courses -> 
     * column id</b>
     * <p>
     * Is a member of db UNIQUE index 3, along with the assignment's 
     * {@link model.Assignment#title title} and {@link model.Assignment#submissionDate submissionDate}
     */
    private int courseId;
    
    /**
     * The title of this assignment [varchar(255) not null]
     * <p>
     * Is a member of db UNIQUE index 3, along with the assignment's 
     * {@link model.Assignment#courseId courseId} and {@link model.Assignment#submissionDate submissionDate}
     */
    private String title;
    
    /**
     * The submission date of this assignment [date not null]
     * <p>
     * Is a member of db UNIQUE index 3, along with the assignment's 
     * {@link model.Assignment#courseId courseId} and {@link model.Assignment#title title}
     */
    private LocalDate submissionDate;
    
    /**
     * The description of this assignment [text null]
     */
    private String description;

    /**
     * Constructor for new assignments (no id yet)
     * 
     * @param courseId int(11) not null. FK(ON DELETE CASCADE) to courses -> id. member of UNIQUE index 3
     * @param title varchar(255) not null. member of UNIQUE index 3
     * @param submissionDate date not null. member of UNIQUE index 3
     * @param description text null
     */
    public Assignment(int courseId, String title, LocalDate submissionDate, String description) {
        this.courseId = courseId;
        this.title = title;
        this.submissionDate = submissionDate;
        this.description = description;
    }
    
    /**
     * Constructor for existing assignments (with id)
     * 
     * @param courseId int(11) not null. FK(ON DELETE CASCADE) to courses -> id. member of UNIQUE index 3
     * @param title varchar(255) not null. member of UNIQUE index 3
     * @param submissionDate date not null. member of UNIQUE index 3
     * @param description text null
     * @param id int(11) auto increment PK
     */
    public Assignment(int courseId, String title, LocalDate submissionDate, String description, int id) {
        this.id = id;
        this.courseId = courseId;
        this.title = title;
        this.submissionDate = submissionDate;
        this.description = description;
    }

    public int getId() {
        return id;
    }

    public int getCourseId() {
        return courseId;
    }

    public String getTitle() {
        return title;
    }

    public LocalDate getSubmissionDate() {
        return submissionDate;
    }

    public String getDescription() {
        return description;
    }

    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setSubmissionDate(LocalDate submissionDate) {
        this.submissionDate = submissionDate;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
