package model;

/**
 * Model of a Course
 * set ONLY by the Headmaster
 * <p>
 * A Course has a {@link model.Course#id unique id}, 
 * a {@link model.Course#title title}, 
 * a {@link model.Course#stream stream} and 
 * a {@link model.Course#type type}. 
 *
 * @author Sakel
 * @version 1.0
 */
public final class Course implements Persistable {

    /**
     * unique identifier of a course [int(11) auto increment PK] 
     * <p>
     * If this is a new course, and not an existing one taken from 
     * the database, then id is allowed to not be instantiated since id
     * will be <b>auto generated by the database</b> once the new course is inserted
     */
    private int id;
    
    /**
     * The title of this course [varchar(255) not null]
     */
    private String title;
    
    /**
     * The stream of this course [enum('java','csharp') not null]
     * <p>
     * For new courses, stream options are enforced by the use of
     * {@link model.Utils.CourseStream Enum Utils.CourseStream}
     * as expected parameter in the appropriate constructor
     */
    private String stream;
    
    /**
     * The type of this course [enum('part','full') not null]
     * <p>
     * For new courses, type options are enforced by the use of
     * {@link model.Utils.CourseType Enum Utils.CourseType}
     * as expected parameter in the appropriate constructor
     */
    private String type;

    /**
     * Constructor for new courses (no id yet)
     *
     * @param title varchar(255) not null
     * @param stream enum('java','c#') not null
     * @param type enum('part','full') not null
     */
    public Course(String title, String stream, String type) {
        this.title = title;
        this.stream = stream;
        this.type = type;
    }

    /**
     * Constructor for existing courses (with id)
     *
     * @param id int(11) auto increment PK
     * @param title varchar(255) not null
     * @param stream enum('java','c#') not null
     * @param type enum('part','full') not null
     */
    public Course(String title, String stream, String type, int id) {
        this.id = id;
        this.title = title;
        this.stream = stream;
        this.type = type;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getStream() {
        return stream;
    }

    public String getType() {
        return type;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setStream(String stream) {
        this.stream = stream;
    }

    public void setType(String type) {
        this.type = type;
    }


}
