package model;

import java.time.LocalDateTime;

/**
 * Model of a Schedule, basically a session of a classroom
 * set ONLY by the Headmaster
 * <p>
 * A Schedule has a {@link model.Schedule#id unique id}, 
 * a {@link model.Schedule#courseId courseId}, 
 * a {@link model.Schedule#start start} and 
 * a {@link model.Schedule#end end}. 
 *
 * @author Sakel
 * @version 1.0
 */
public final class Schedule implements Persistable {

    /**
     * unique identifier of a schedule [int(11) auto increment PK] 
     * <p>
     * If this is a new schedule, and not an existing one taken from 
     * the database, then id is allowed to not be instantiated since id
     * will be <b>auto generated by the database</b> once the new schedule is inserted
     */
    private int id;
    
    /**
     * identifier of the course this schedule belongs to [int(11) not null]
     * <p>
     * If this is a new schedule then courseId must be provided explicitly
     * and has to belong to an existing course from the database
     * <p>
     * If this is an existing schedule taken from the database then courseId
     * is provided by the database and is a <b>FK pointing to table courses -> 
     * column id</b>
     */
    private int courseId;
    
    /**
     * This schedule's start date/time [datetime not null]
     */
    private LocalDateTime start;
    
    /**
     * This schedule's end date/time [datetime not null]
     */
    private LocalDateTime end;

    /**
     * Constructor for new schedules (no id yet)
     * 
     * @param courseId int(11) not null. FK to courses -> id
     * @param start datetime not null
     * @param end datetime not null
     */
    public Schedule(int courseId, LocalDateTime start, LocalDateTime end) {
        this.courseId = courseId;
        this.start = start;
        this.end = end;
    }
    
    /**
     * Constructor for existing schedules (with id)
     * 
     * @param id int(11) auto increment PK
     * @param courseId int(11) not null. FK to courses -> id
     * @param start datetime not null
     * @param end datetime not null
     */
    public Schedule(int courseId, LocalDateTime start, LocalDateTime end, int id) {
        this.id = id;
        this.courseId = courseId;
        this.start = start;
        this.end = end;
    }

    public int getId() {
        return id;
    }

    public int getCourseId() {
        return courseId;
    }

    public LocalDateTime getStart() {
        return start;
    }

    public LocalDateTime getEnd() {
        return end;
    }

    void setCourseId(int courseId) {
        this.courseId = courseId;
    }

    void setStart(LocalDateTime start) {
        this.start = start;
    }

    void setEnd(LocalDateTime end) {
        this.end = end;
    }

}
