/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DBAccess;
import java.awt.CardLayout;
import java.lang.reflect.InvocationTargetException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.sql.SQLException;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.User;

/**
 *
 * @author Sakel
 */
public class MainWindow extends javax.swing.JFrame {
    
    private TreeMap<String, UserMenu> userMenus;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        userMenus = new TreeMap();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        loginScreen = new javax.swing.JPanel();
        start_usernameField = new javax.swing.JTextField();
        start_usernameLabel = new javax.swing.JLabel();
        start_passwordField = new javax.swing.JPasswordField();
        start_passwordLabel = new javax.swing.JLabel();
        start_loginButton = new javax.swing.JButton();
        start_headmasterInfoLabel = new javax.swing.JLabel();
        start_usernameErrorLabel = new javax.swing.JLabel();
        start_passwordErrorLabel = new javax.swing.JLabel();
        start_loginErrorLabel = new javax.swing.JLabel();
        headmasterMenuScreen = new view.headmaster.HeadmasterMenu();
        studentMenuScreen = new view.student.StudentMenu();
        trainerMenuScreen = new view.trainer.TrainerMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Private School");

        mainPanel.setLayout(new java.awt.CardLayout());

        start_usernameLabel.setText("Username");

        start_passwordLabel.setText("Password");

        start_loginButton.setText("Login");
        start_loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_loginButtonActionPerformed(evt);
            }
        });

        start_headmasterInfoLabel.setText("<html>Headmaster login credentials<br>Username : <i style=\"color:green\">admin </i><br>Password : <i style=\"color:green\">ILoveJava</i></html>");

        javax.swing.GroupLayout loginScreenLayout = new javax.swing.GroupLayout(loginScreen);
        loginScreen.setLayout(loginScreenLayout);
        loginScreenLayout.setHorizontalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                        .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(start_loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_passwordErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_usernameErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(410, 410, 410))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                        .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(start_headmasterInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_loginErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(372, 372, 372)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        loginScreenLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {start_passwordErrorLabel, start_passwordField, start_passwordLabel, start_usernameErrorLabel, start_usernameField, start_usernameLabel});

        loginScreenLayout.setVerticalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(start_usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(start_usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(start_usernameErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(start_passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(start_passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(start_passwordErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(start_loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(start_headmasterInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(start_loginErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        loginScreenLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {start_passwordField, start_usernameField});

        loginScreenLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {start_passwordErrorLabel, start_usernameErrorLabel});

        loginScreenLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {start_passwordLabel, start_usernameLabel});

        mainPanel.add(loginScreen, "loginScreenCard");
        mainPanel.add(headmasterMenuScreen, "headmasterMenuScreenCard");
        userMenus.put("headmaster", headmasterMenuScreen);
        mainPanel.add(studentMenuScreen, "studentMenuScreenCard");
        userMenus.put("student", studentMenuScreen);
        mainPanel.add(trainerMenuScreen, "trainerMenuScreenCard");
        userMenus.put("trainer", trainerMenuScreen);

        jMenu1.setText("User");

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * username AND password have been entered into login form, 
     * time to query the database and login or not
     * @param evt 
     */
    private void start_loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_loginButtonActionPerformed
        
        if ( start_usernameField.getText().length() > 0 ) {
            if ( start_passwordField.getPassword().length > 0 ) {
                      
                try {
                    
                    DBAccess access = DBAccess.singleton();

                    //authenticate user
                    access.connectUser(start_usernameField.getText(), start_passwordField.getPassword());
                    User user = access.getUser();

                    if ( user != null ){

                        CardLayout card = (CardLayout)mainPanel.getLayout();

                        //show appropriate card for user type
                        card.show(mainPanel, user.getType() + "MenuScreenCard");
                        setTitle("Welcome " + user.getUsername());

                        //populate user specific menu
                        userMenus.get(user.getType()).initUserMenu();

                    }
                    else{
                        Actions.setLabelWithTimeoutMsg("<html><b style=\"color:red\">User doesn't exist. Please try again</b></html>", 3000, start_loginErrorLabel);
                    }


                } catch (SQLException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                    for(Throwable e : ex){
                        System.err.println(e);
                    }
                } catch (ClassNotFoundException | NoSuchMethodException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException | NoSuchAlgorithmException | InvalidKeySpecException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            else {
                Actions.setLabelWithTimeoutMsg("<html><b style=\"color:red\">Please enter a password</b></html>", 3000, start_passwordErrorLabel);
            }
        }
        else {
            Actions.setLabelWithTimeoutMsg("<html><b style=\"color:red\">Please enter a username</b></html>", 3000, start_usernameErrorLabel);
        }
        
    }//GEN-LAST:event_start_loginButtonActionPerformed

    /**
     * User Log out
     * 
     * @param evt 
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        CardLayout card = (CardLayout)mainPanel.getLayout();

        try {
            //show login screen
            DBAccess.reset();
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        card.show(mainPanel, "loginScreenCard");
        setTitle("Private School");
  
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.headmaster.HeadmasterMenu headmasterMenuScreen;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel start_headmasterInfoLabel;
    private javax.swing.JButton start_loginButton;
    private javax.swing.JLabel start_loginErrorLabel;
    private javax.swing.JLabel start_passwordErrorLabel;
    private javax.swing.JPasswordField start_passwordField;
    private javax.swing.JLabel start_passwordLabel;
    private javax.swing.JLabel start_usernameErrorLabel;
    private javax.swing.JTextField start_usernameField;
    private javax.swing.JLabel start_usernameLabel;
    private view.student.StudentMenu studentMenuScreen;
    private view.trainer.TrainerMenu trainerMenuScreen;
    // End of variables declaration//GEN-END:variables
}
